[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[package]
name = "feagi_rust_py_libs"
version = "0.0.45"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "feagi_rust_py_libs"
crate-type = ["cdylib"]

[dependencies]
feagi_connector_core = { version = "0.0.50-beta.13"}
feagi_data_serialization = { version = "0.0.50-beta.13"}
feagi_data_structures = { version = "0.0.50-beta.13"}
numpy = "0.24.0"
ndarray = "0.16.1"
paste = "1.0"

[build-dependencies]
feagi_data_structures = { version = "0.0.50-beta.13"}


[dependencies.pyo3]
version = "0.24.2"
features = ["abi3-py38"] # "abi3-py38" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.8

