[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[package]
name = "feagi_rust_py_libs"
version = "0.0.76"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "feagi_rust_py_libs"
crate-type = ["cdylib"]

[dependencies]
feagi_connector_core = "0.0.50-beta.59"
feagi_data_serialization = "0.0.50-beta.59"
feagi_data_structures = "0.0.50-beta.59"
#feagi-agent-sdk = { path = "../feagi-core/crates/feagi-agent-sdk" }
#feagi-pns = { path = "../feagi-core/crates/feagi-pns" }
#feagi-evo = { path = "../feagi-core/crates/feagi-evo" }
numpy = "0.24.0"
ndarray = "0.16.1"
paste = "1.0"
serde_json = "1"
zmq = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
feagi_data_structures = "0.0.50-beta.59"

[dependencies.pyo3]
version = "0.27.2"
features = ["abi3-py38", "multiple-pymethods"] # "abi3-py38" tells pyo3 (and maturin) to rust_build_scripts using the stable ABI with minimum Python version 3.8

